"""
Comprehensive Legal Disclaimers and Liability Protection for SmartDispute.ai
This module provides standardized disclaimers to protect the platform and clarify the nature of services.
"""

def get_comprehensive_liability_disclaimer() -> str:
    """
    Main liability disclaimer for the platform
    """
    return """
IMPORTANT LEGAL DISCLAIMER AND LIABILITY LIMITATION

SmartDispute.ai is NOT a law firm, legal practice, or legal service provider. Our platform and AI system do NOT provide legal advice, and no attorney-client relationship is created through use of our services.

NATURE OF SERVICE:
• We provide legal information, document templates, and procedural guidance only
• Our AI analyzes documents and generates forms based on publicly available legal information
• All content is for informational and educational purposes only
• Every legal situation is unique and requires individual consideration

NO LEGAL ADVICE:
• Nothing on this platform constitutes legal advice for your specific situation
• We do not provide recommendations about whether you should pursue legal action
• All legal decisions remain solely your responsibility
• Consult with a qualified lawyer for legal advice

LIMITATION OF LIABILITY:
TO THE MAXIMUM EXTENT PERMITTED BY LAW, SMARTDISPUTE.AI, ITS CREATOR, EMPLOYEES, AND AFFILIATES SHALL NOT BE LIABLE FOR:
• Any direct, indirect, incidental, special, consequential, or punitive damages
• Any loss of profits, data, use, goodwill, or other intangible losses
• Any damages resulting from your use or inability to use our services
• Any reliance on information, documents, or analysis provided by our platform
• Any legal outcomes, court decisions, or case results
• Any errors, omissions, or inaccuracies in generated documents or analysis

USER RESPONSIBILITY:
By using SmartDispute.ai, you acknowledge and agree that:
• You are solely responsible for all legal decisions and actions
• You will verify all information and legal requirements independently
• You understand that laws change frequently and our information may not be current
• You will seek professional legal advice when appropriate
• You use our services at your own risk

ACCURACY DISCLAIMER:
• Legal information may not be current, complete, or applicable to your situation
• Court forms and procedures change regularly
• AI analysis is based on algorithms and may contain errors
• Always verify current laws, rules, and procedures with official sources

PROFESSIONAL CONSULTATION RECOMMENDED:
We strongly recommend consulting with a qualified lawyer for:
• Complex legal matters
• Cases involving significant money, property, or rights
• Criminal law matters
• Family law involving children
• Any situation where you feel uncertain

This disclaimer is governed by Canadian law. If any portion is found unenforceable, the remainder shall remain in full force and effect.

By continuing to use SmartDispute.ai, you acknowledge that you have read, understood, and agree to these terms.
"""

def get_footer_disclaimer() -> str:
    """
    Shorter disclaimer for page footers
    """
    return """
SmartDispute.ai provides legal information, not legal advice. We are not lawyers. 
All legal decisions are your responsibility. Consult a qualified lawyer for legal advice.
"""

def get_form_generation_disclaimer() -> str:
    """
    Specific disclaimer for AI-generated court forms
    """
    return """
AI-GENERATED DOCUMENT DISCLAIMER:

This document was generated by artificial intelligence based on your input and publicly available legal templates. 

IMPORTANT WARNINGS:
• This is NOT a substitute for professional legal drafting
• AI may not capture all nuances of your specific situation
• Court rules and requirements change frequently
• Filing incorrect or incomplete documents may harm your case

BEFORE FILING:
✓ Review all information for accuracy and completeness
✓ Verify current court rules and procedures
✓ Consider legal consultation for complex matters
✓ Ensure all deadlines and requirements are met

You are solely responsible for the accuracy and appropriateness of all filed documents.
"""

def get_evidence_analysis_disclaimer() -> str:
    """
    Disclaimer for AI evidence analysis
    """
    return """
AI EVIDENCE ANALYSIS DISCLAIMER:

Our AI system has analyzed your documents and provided an assessment. This analysis:

• Is based on algorithms and pattern recognition, not legal expertise
• May not identify all relevant legal issues or evidence
• Cannot guarantee accuracy of merit score or predictions
• Does not consider all possible legal strategies or defenses
• Should not be your only basis for legal decisions

A qualified lawyer may identify additional issues, evidence, or strategies not captured by our AI analysis.
"""

def get_merit_score_disclaimer() -> str:
    """
    Disclaimer for merit score assessments
    """
    return """
MERIT SCORE DISCLAIMER:

The merit score is an AI-generated assessment based on:
• Document analysis algorithms
• Pattern matching with legal databases
• Statistical modeling of similar cases

LIMITATIONS:
• Cannot predict actual court outcomes
• Based on submitted documents only
• Does not account for opposing party evidence
• Legal standards and interpretation vary by judge
• Settlement possibilities not fully considered

This score is for guidance only and should not be your sole basis for legal decisions.
"""

def get_self_representation_disclaimer() -> str:
    """
    Disclaimer for self-representation confidence assessments
    """
    return """
SELF-REPRESENTATION ASSESSMENT DISCLAIMER:

Our confidence assessment for self-representation is based on:
• Case type complexity
• Document strength analysis
• General procedural requirements

IMPORTANT CONSIDERATIONS:
• Your comfort level with legal procedures
• Available time for case preparation
• Stress tolerance for court proceedings
• Ability to present evidence effectively
• Understanding of legal concepts and terminology

Even with "high confidence" assessment, legal representation may be beneficial. 
Even with "low confidence" assessment, self-representation may be successful with proper preparation.

The decision to represent yourself is entirely personal and depends on factors beyond our analysis.
"""

def get_settlement_disclaimer() -> str:
    """
    Disclaimer for settlement recommendations
    """
    return """
SETTLEMENT RECOMMENDATION DISCLAIMER:

Settlement suggestions are based on general case analysis and do not consider:
• Your personal priorities and needs
• Opposing party's specific circumstances
• Non-monetary factors important to you
• Future relationship considerations
• Tax implications of settlement terms

Settlement decisions should consider factors beyond monetary value and legal merit.
Consult appropriate professionals for tax, financial, or other specialized advice.
"""

def get_timeline_cost_disclaimer() -> str:
    """
    Disclaimer for timeline and cost estimates
    """
    return """
TIMELINE AND COST ESTIMATE DISCLAIMER:

Estimates are based on general averages and may not reflect your specific situation:

TIMELINE FACTORS:
• Court scheduling varies significantly
• Case complexity affects duration
• Settlement negotiations can extend or shorten process
• Appeals or enforcement may add significant time

COST FACTORS:
• Court fees change periodically
• Additional costs may arise unexpectedly
• Professional services costs vary widely
• Opportunity costs of time investment

Actual timelines and costs may vary significantly from estimates.
Budget for potential additional time and expenses.
"""

def get_jurisdictional_disclaimer() -> str:
    """
    Disclaimer for jurisdictional information
    """
    return """
JURISDICTIONAL INFORMATION DISCLAIMER:

Legal information is provided for Canadian jurisdictions based on publicly available sources:

LIMITATIONS:
• Laws and procedures change frequently
• Municipal bylaws and court rules vary
• Federal vs. provincial jurisdiction can be complex
• Indigenous law considerations may apply
• International law issues not addressed

Always verify current laws and procedures with official government sources or legal professionals.
"""

def get_privacy_data_disclaimer() -> str:
    """
    Privacy and data use disclaimer
    """
    return """
PRIVACY AND DATA USE DISCLAIMER:

PILOT PROGRAM DATA COLLECTION:
• We are collecting data from our first 1000 users for research and improvement
• Your case information helps us enhance our AI system
• Data is anonymized and aggregated for analysis
• Individual cases are not shared or published
• You may request data deletion at any time

CONFIDENTIALITY LIMITATIONS:
• We are not bound by attorney-client privilege
• Data may be subject to legal disclosure requirements
• Cloud storage providers may have access to encrypted data
• No guarantee of absolute confidentiality

For matters requiring absolute confidentiality, consult with a lawyer directly.
"""

def get_ai_limitations_disclaimer() -> str:
    """
    Disclaimer about AI system limitations
    """
    return """
ARTIFICIAL INTELLIGENCE LIMITATIONS:

Our AI system has inherent limitations:

TECHNICAL LIMITATIONS:
• Based on training data with potential biases
• Cannot understand context like human lawyers
• May miss nuanced legal arguments
• Cannot provide creative legal strategies
• Limited to programmed legal knowledge

KNOWLEDGE LIMITATIONS:
• Training data has a specific cutoff date
• Cannot access real-time legal developments
• May not include recent case law or legislative changes
• Cannot account for local court practices or judge preferences

DECISION-MAKING LIMITATIONS:
• Cannot make value judgments about your priorities
• Cannot assess credibility of witnesses or parties
• Cannot predict human behavior in legal proceedings
• Cannot adapt strategy based on unexpected developments

Human legal expertise remains superior for complex, nuanced, or high-stakes matters.
"""

def get_emergency_legal_disclaimer() -> str:
    """
    Disclaimer for emergency legal situations
    """
    return """
EMERGENCY LEGAL SITUATIONS:

SmartDispute.ai is NOT appropriate for emergency legal situations requiring immediate action:

SEEK IMMEDIATE LEGAL HELP FOR:
• Criminal charges or arrests
• Court orders or injunctions against you
• Imminent eviction or foreclosure
• Child protection proceedings
• Domestic violence situations
• Immigration detention or deportation
• Tax seizure or audit
• Any situation with immediate deadlines

For emergency legal situations, contact:
• Legal Aid services in your province
• Law Society of your province lawyer referral service
• Community legal clinics
• Duty counsel at local courts

Do not rely on our platform for time-sensitive legal matters.
"""

def get_success_rate_disclaimer() -> str:
    """
    Disclaimer about success predictions
    """
    return """
SUCCESS RATE AND OUTCOME DISCLAIMER:

No prediction of legal success or outcomes is guaranteed:

UNPREDICTABLE FACTORS:
• Judge or tribunal member discretion
• Quality of opposing representation
• Credibility assessments during hearings
• New evidence discovered during proceedings
• Changes in law or legal interpretation
• Settlement negotiations and dynamics

PAST RESULTS DISCLAIMER:
• Past case results do not guarantee future outcomes
• Every case is unique with specific circumstances
• Legal precedents may not apply to your situation
• Our AI analysis cannot predict these variables

Success depends on many factors beyond case merit and document quality.
Prepare for various possible outcomes and have contingency plans.
"""

def get_complete_terms_of_service() -> str:
    """
    Complete terms of service incorporating all disclaimers
    """
    return f"""
SMARTDISPUTE.AI TERMS OF SERVICE AND COMPREHENSIVE DISCLAIMERS

{get_comprehensive_liability_disclaimer()}

ADDITIONAL SPECIFIC DISCLAIMERS:

1. AI-GENERATED DOCUMENTS
{get_form_generation_disclaimer()}

2. EVIDENCE ANALYSIS
{get_evidence_analysis_disclaimer()}

3. MERIT SCORES
{get_merit_score_disclaimer()}

4. SELF-REPRESENTATION ASSESSMENT
{get_self_representation_disclaimer()}

5. SETTLEMENT RECOMMENDATIONS
{get_settlement_disclaimer()}

6. TIMELINE AND COST ESTIMATES
{get_timeline_cost_disclaimer()}

7. JURISDICTIONAL INFORMATION
{get_jurisdictional_disclaimer()}

8. PRIVACY AND DATA USE
{get_privacy_data_disclaimer()}

9. AI SYSTEM LIMITATIONS
{get_ai_limitations_disclaimer()}

10. EMERGENCY SITUATIONS
{get_emergency_legal_disclaimer()}

11. SUCCESS PREDICTIONS
{get_success_rate_disclaimer()}

ACCEPTANCE OF TERMS:
By using SmartDispute.ai, you acknowledge that you have read, understood, and agree to all of these terms and disclaimers. If you do not agree, please discontinue use of our services immediately.

CREATOR'S MISSION:
SmartDispute.ai was created to help bridge the gap in legal access for Canadians who cannot afford lawyers. Our creator is not a lawyer but recognized a significant need in the market for accessible legal information and document preparation tools. This platform aims to empower individuals with information and tools while maintaining appropriate boundaries about the nature of services provided.

Last Updated: June 28, 2025
"""